# Pandas

The `numpy` module is excellent for numerical computations, but to handle missing data or arrays with mixed types takes more work. The `pandas` module is currently the most widely used tool for data manipulation, providing high-performance, easy-to-use data structures and advanced data analysis tools.

In particular `pandas` features:

* A fast and efficient "DataFrame" object for data manipulation with integrated indexing;
* Tools for reading and writing data between in-memory data structures and different formats (CSV, Excel, SQL, HDF5);
* Intelligent data alignment and integrated handling of missing data;
* Intelligent label-based slicing, fancy indexing, and subsetting of large data sets;
* Aggregating or transforming data with a powerful "group-by" engine; 
* High performance merging and joining of data sets;
* Hierarchical axis indexing provides an intuitive way of working with high-dimensional data in a lower-dimensional data structure;
* Time series-functionalities;
* Highly optimized for performance, with critical code paths written in Cython or C.

In [86]:
import pandas as pd
import numpy as np

In [87]:
import os
os.getcwd()

'C:\\Users\\itter\\UNIPD 1st year programming\\LaboratoryOfComputationalPhysics_Y8'

## Series

Series are completely equivalent to 1D array but with axis labels and the possibility to store heterogeneous elements. Of paramount importance are the time-series, used to define time evolutions of a phenomenon.

In [3]:
from string import ascii_lowercase as letters

# Creating a series, accessing indexes, values and values by their index 
xs = pd.Series(np.arange(10)*0.5, index=tuple(letters[:10]))
print ("xs:", xs,'\n')
print ("xs indexes:",xs.index,'\n')
# Values of the Series are actually a numpy array
print ("xs values:", xs.values, type(xs.values),'\n')
print (xs['f'], xs.f, xs.h, '\n')
print (xs[['d', 'f', 'h']], '\n')
print (type(xs[['d', 'f', 'h']]), '\n')

xs: a    0.0
b    0.5
c    1.0
d    1.5
e    2.0
f    2.5
g    3.0
h    3.5
i    4.0
j    4.5
dtype: float64

xs indexes: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

xs values: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] <class 'numpy.ndarray'>

2.5 2.5 3.5

d    1.5
f    2.5
h    3.5
dtype: float64

<class 'pandas.core.series.Series'>

In [4]:
# Extracting elements and operations: same as numpy array
print (xs[:3],'\n')
print (xs[7:], '\n')
print (xs[::3], '\n')
print (xs[xs>3], '\n')
print (np.exp(xs), '\n')
print (np.mean(xs), np.std(xs), '\n')

a    0.0
b    0.5
c    1.0
dtype: float64

h    3.5
i    4.0
j    4.5
dtype: float64

a    0.0
d    1.5
g    3.0
j    4.5
dtype: float64

h    3.5
i    4.0
j    4.5
dtype: float64

a     1.000000
b     1.648721
c     2.718282
d     4.481689
e     7.389056
f    12.182494
g    20.085537
h    33.115452
i    54.598150
j    90.017131
dtype: float64

2.25 1.4361406616345072

In [5]:
# Series can be created from python dictionary too.
# Notice that the elements can be whatever!
d = {'b' : 1, 'a' : 'cat', 'c' : [2,3]}
pd.Series(d)

b         1
a       cat
c    [2, 3]
dtype: object

A key difference between Series and nparray is that operations between Series automatically align the data based on label. Thus, you can write computations without considering whether the Series involved have the same labels.

In [6]:
s = pd.Series(np.random.randn(5), index=tuple(letters[:5]))
print(s)
s = s[1:] + s[:-1]
print(s)

a   -0.747965
b    0.418848
c    0.654318
d   -0.373124
e    0.253304
dtype: float64
a         NaN
b    0.837696
c    1.308636
d   -0.746249
e         NaN
dtype: float64

### Time series

Time series are very often used to profile the behaviour of a quantity as a function of time. Pandas has a special index for that, `DatetimeIndex`, that can be created e.g. with the function `pd.data_range()`

In [7]:
# to define a date, the datetime module is very useful
import datetime as dt
date = dt.date.today()
print(date)

date = dt.datetime(2025,11,26,10,45,10,15)
print (date)

# otherwise, several notations are interpreted too
date = 'Nov 26 2025'
# or alternatively
#date = '26/11/2025 10:45:00'
print (date)

days2 = pd.date_range(date, periods=7, freq='2D') # Create 7 consecutive dates starting from `date`, one each 2 days (D = daily).
print (days2)

seconds = pd.date_range(date, periods=3600, freq='s')
print (seconds)

2025-12-25
2025-11-26 10:45:10.000015
Nov 26 2025
DatetimeIndex(['2025-11-26', '2025-11-28', '2025-11-30', '2025-12-02',
               '2025-12-04', '2025-12-06', '2025-12-08'],
              dtype='datetime64[ns]', freq='2D')
DatetimeIndex(['2025-11-26 00:00:00', '2025-11-26 00:00:01',
               '2025-11-26 00:00:02', '2025-11-26 00:00:03',
               '2025-11-26 00:00:04', '2025-11-26 00:00:05',
               '2025-11-26 00:00:06', '2025-11-26 00:00:07',
               '2025-11-26 00:00:08', '2025-11-26 00:00:09',
               ...
               '2025-11-26 00:59:50', '2025-11-26 00:59:51',
               '2025-11-26 00:59:52', '2025-11-26 00:59:53',
               '2025-11-26 00:59:54', '2025-11-26 00:59:55',
               '2025-11-26 00:59:56', '2025-11-26 00:59:57',
               '2025-11-26 00:59:58', '2025-11-26 00:59:59'],
              dtype='datetime64[ns]', length=3600, freq='s')

To learn more about the frequency strings, please see this [link](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)


Timestamped data is the most basic type of time series data that associates values with points in time. For pandas objects it means using the points in time.

functions like `pd.to_datetime` can be used, for instance, when reading information as string from a dataset.

Timestamp is the pandas equivalent of python’s Datetime and is interchangeable with it in most cases.

In [8]:
tstamp = pd.Timestamp(dt.datetime(2020, 11, 9))

# internally it counts the nanoseconds from January 1st 1970
# tstamp = pd.Timestamp(dt.datetime(1970, 1, 1, 0, 0, 0, 1)) # Last value is for microseconds.
print(tstamp.value) # Notice that `.value` gives the integer (nanoseconds since 1970-01-01 UTC) used internally to store the Timestamp.

# when creating a timestamp the format can be explicitly passed
ts = pd.to_datetime('2010/11/12', format='%Y/%m/%d')
print (type(ts))
print (ts.value)
ts = pd.to_datetime('12-11-2010 00:00', format='%d-%m-%Y %H:%M')
print (ts)
print (ts.value)

1604880000000000000
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
1289520000000000000
2010-11-12 00:00:00
1289520000000000000

A standard series can be created and (range of) elements can be used as indexes

In [9]:
tseries = pd.Series(np.random.normal(10, 1, len(days2)), index=days2)
# Extracting elements
print (tseries[0:4], '\n')
print (tseries['2025-11-26':'2025-12-02'], '\n') # Note - includes end time

2025-11-26    10.014815
2025-11-28     9.476940
2025-11-30    10.573147
2025-12-02    10.936856
Freq: 2D, dtype: float64

2025-11-26    10.014815
2025-11-28     9.476940
2025-11-30    10.573147
2025-12-02    10.936856
Freq: 2D, dtype: float64

`pd.to_datetime` can also be used to create a `DatetimeIndex`:

In [10]:
pd.to_datetime([1, 2, 3, 4], unit='D', origin=pd.Timestamp('1980-02-03'))

DatetimeIndex(['1980-02-04', '1980-02-05', '1980-02-06', '1980-02-07'], dtype='datetime64[ns]', freq=None)

## DataFrame

A pandas DataFrame is like a simple tabular spreadsheet. For future reference (or for people already familiar with R), a pandas DataFrame is very similar to the R DataFrame.

Each column in a DataFrame is a Series object.

The element can be whatever, missing data is also treated (as NaN)

### DataFrame creation

A DataFrame can be created implicitly, with, e.g., a DatatimeIndex object as index:

In [11]:
entries=10
dates=pd.date_range('11/26/2025 10:45:00',freq='h', periods=entries)
df = pd.DataFrame(np.random.randn(entries,4), index=dates, columns=['A','B','C','D'])
df

                            A         B         C         D
2025-11-26 10:45:00 -1.330216 -1.835610 -0.304355 -0.025054
2025-11-26 11:45:00  1.654689  1.110970 -0.895581 -0.187253
2025-11-26 12:45:00  1.886450  2.539469  0.844874  0.479326
2025-11-26 13:45:00  0.062134  0.066643 -0.580331  2.162716
2025-11-26 14:45:00  1.105816  1.055264  0.541669  1.183234
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  0.332705
2025-11-26 16:45:00 -1.113811  0.163264  0.161566 -0.770786
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319 -0.443927
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806  0.684370
2025-11-26 19:45:00  2.188733 -0.023291  2.685807 -0.120894

or by means of a dictionary:

In [12]:
df2 = pd.DataFrame(
    { 'A' : 1.,
      'B' : pd.Timestamp('20130102'),
      'C' : pd.Series(1,index=range(4),dtype='float32'),
      'D' : np.arange(7,11),
      'E' : pd.Categorical(["test","train","test","train"]),
    }
    )
df2

# All arrays must be of the same length.
# "pd.Categorical" is a pandas type for data with a limited set of discrete values (e.g., "test"/"train").

     A          B    C   D      E
0  1.0 2013-01-02  1.0   7   test
1  1.0 2013-01-02  1.0   8  train
2  1.0 2013-01-02  1.0   9   test
3  1.0 2013-01-02  1.0  10  train

### Viewing Data

In [13]:
df.head(2)

                            A        B         C         D
2025-11-26 10:45:00 -1.330216 -1.83561 -0.304355 -0.025054
2025-11-26 11:45:00  1.654689  1.11097 -0.895581 -0.187253

In [14]:
df.tail(4)

                            A         B         C         D
2025-11-26 16:45:00 -1.113811  0.163264  0.161566 -0.770786
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319 -0.443927
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806  0.684370
2025-11-26 19:45:00  2.188733 -0.023291  2.685807 -0.120894

In [15]:
df.index

DatetimeIndex(['2025-11-26 10:45:00', '2025-11-26 11:45:00',
               '2025-11-26 12:45:00', '2025-11-26 13:45:00',
               '2025-11-26 14:45:00', '2025-11-26 15:45:00',
               '2025-11-26 16:45:00', '2025-11-26 17:45:00',
               '2025-11-26 18:45:00', '2025-11-26 19:45:00'],
              dtype='datetime64[ns]', freq='h')

In [16]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [17]:
df.values

array([[-1.33021565, -1.83560983, -0.30435531, -0.02505398],
       [ 1.65468888,  1.11097036, -0.8955815 , -0.18725284],
       [ 1.88645023,  2.53946886,  0.84487402,  0.47932581],
       [ 0.06213435,  0.06664311, -0.58033145,  2.16271633],
       [ 1.1058155 ,  1.05526411,  0.54166892,  1.18323422],
       [-0.54971746,  0.26221678,  1.15424219,  0.332705  ],
       [-1.11381064,  0.16326448,  0.16156589, -0.77078556],
       [ 0.53320105, -0.11192502, -0.92631916, -0.44392658],
       [-2.00868777, -0.69507387, -0.3458064 ,  0.68436996],
       [ 2.18873264, -0.02329122,  2.685807  , -0.12089396]])

In [18]:
df.describe()

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.242859   0.253193   0.233576   0.329444
std     1.466496   1.160517   1.117672   0.859092
min    -2.008688  -1.835610  -0.926319  -0.770786
25%    -0.972787  -0.089767  -0.521700  -0.170663
50%     0.297668   0.114954  -0.071395   0.153826
75%     1.517471   0.857002   0.769073   0.633109
max     2.188733   2.539469   2.685807   2.162716

In [19]:
df.T

,2025-11-26 10:45:00,2025-11-26 11:45:00,2025-11-26 12:45:00,2025-11-26 13:45:00,2025-11-26 14:45:00,2025-11-26 15:45:00,2025-11-26 16:45:00,2025-11-26 17:45:00,2025-11-26 18:45:00,2025-11-26 19:45:00
A,-1.330216,1.654689,1.886450,0.062134,1.105816,-0.549717,-1.113811,0.533201,-2.008688,2.188733
B,-1.835610,1.110970,2.539469,0.066643,1.055264,0.262217,0.163264,-0.111925,-0.695074,-0.023291
C,-0.304355,-0.895581,0.844874,-0.580331,0.541669,1.154242,0.161566,-0.926319,-0.345806,2.685807
D,-0.025054,-0.187253,0.479326,2.162716,1.183234,0.332705,-0.770786,-0.443927,0.684370,-0.120894

In [20]:
df.sort_index(axis=0,ascending=False) # "axis = 1" changes the columns.

                            A         B         C         D
2025-11-26 19:45:00  2.188733 -0.023291  2.685807 -0.120894
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806  0.684370
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319 -0.443927
2025-11-26 16:45:00 -1.113811  0.163264  0.161566 -0.770786
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  0.332705
2025-11-26 14:45:00  1.105816  1.055264  0.541669  1.183234
2025-11-26 13:45:00  0.062134  0.066643 -0.580331  2.162716
2025-11-26 12:45:00  1.886450  2.539469  0.844874  0.479326
2025-11-26 11:45:00  1.654689  1.110970 -0.895581 -0.187253
2025-11-26 10:45:00 -1.330216 -1.835610 -0.304355 -0.025054

In [21]:
df.sort_values(by="C") # Sorts the rows of the DataFrame df based on the values in column "C", in ascending order by default.

                            A         B         C         D
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319 -0.443927
2025-11-26 11:45:00  1.654689  1.110970 -0.895581 -0.187253
2025-11-26 13:45:00  0.062134  0.066643 -0.580331  2.162716
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806  0.684370
2025-11-26 10:45:00 -1.330216 -1.835610 -0.304355 -0.025054
2025-11-26 16:45:00 -1.113811  0.163264  0.161566 -0.770786
2025-11-26 14:45:00  1.105816  1.055264  0.541669  1.183234
2025-11-26 12:45:00  1.886450  2.539469  0.844874  0.479326
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  0.332705
2025-11-26 19:45:00  2.188733 -0.023291  2.685807 -0.120894

## Selection

### Getting slices

The following show how to get part of the DataFrame (i.e. not just the elements)

In [22]:
## standard and safe
print (df['A'],'\n')

## equivalent but dangerous [imagine blank spaces in the name of the column (as A B for example)].
print (df.A)

2025-11-26 10:45:00   -1.330216
2025-11-26 11:45:00    1.654689
2025-11-26 12:45:00    1.886450
2025-11-26 13:45:00    0.062134
2025-11-26 14:45:00    1.105816
2025-11-26 15:45:00   -0.549717
2025-11-26 16:45:00   -1.113811
2025-11-26 17:45:00    0.533201
2025-11-26 18:45:00   -2.008688
2025-11-26 19:45:00    2.188733
Freq: h, Name: A, dtype: float64

2025-11-26 10:45:00   -1.330216
2025-11-26 11:45:00    1.654689
2025-11-26 12:45:00    1.886450
2025-11-26 13:45:00    0.062134
2025-11-26 14:45:00    1.105816
2025-11-26 15:45:00   -0.549717
2025-11-26 16:45:00   -1.113811
2025-11-26 17:45:00    0.533201
2025-11-26 18:45:00   -2.008688
2025-11-26 19:45:00    2.188733
Freq: h, Name: A, dtype: float64

In [23]:
# selecting rows by counting
print (df[0:3])

# or by index
print (df["2025-11-26 10:45:00":"2025-11-26 12:45:00"])

                            A         B         C         D
2025-11-26 10:45:00 -1.330216 -1.835610 -0.304355 -0.025054
2025-11-26 11:45:00  1.654689  1.110970 -0.895581 -0.187253
2025-11-26 12:45:00  1.886450  2.539469  0.844874  0.479326
                            A         B         C         D
2025-11-26 10:45:00 -1.330216 -1.835610 -0.304355 -0.025054
2025-11-26 11:45:00  1.654689  1.110970 -0.895581 -0.187253
2025-11-26 12:45:00  1.886450  2.539469  0.844874  0.479326

### Selection by label

In [24]:
# getting a cross section (part of the DataFrame) using a label
df.loc[dates[0]]

A   -1.330216
B   -1.835610
C   -0.304355
D   -0.025054
Name: 2025-11-26 10:45:00, dtype: float64

In [25]:
# selecting on a multi-axis by label:
df.loc[:,['A','B']]
#a=df.loc[:,['A','B']]

                            A         B
2025-11-26 10:45:00 -1.330216 -1.835610
2025-11-26 11:45:00  1.654689  1.110970
2025-11-26 12:45:00  1.886450  2.539469
2025-11-26 13:45:00  0.062134  0.066643
2025-11-26 14:45:00  1.105816  1.055264
2025-11-26 15:45:00 -0.549717  0.262217
2025-11-26 16:45:00 -1.113811  0.163264
2025-11-26 17:45:00  0.533201 -0.111925
2025-11-26 18:45:00 -2.008688 -0.695074
2025-11-26 19:45:00  2.188733 -0.023291

In [26]:
# showing label slicing, both endpoints are included:
df.loc['2025-11-26 14:45:00':'2025-11-26 16:45:00',['A','B']]

                            A         B
2025-11-26 14:45:00  1.105816  1.055264
2025-11-26 15:45:00 -0.549717  0.262217
2025-11-26 16:45:00 -1.113811  0.163264

In [27]:
# getting an individual element
print (df.loc[dates[1],'A'])

# equivalently
print (df.at[dates[1],'A'])

1.6546888810119411
1.6546888810119411

### Selecting by position

In [28]:
# select via the position of the passed integers:
print (df.iloc[3],'\n')

# notation similar to numpy/python
print (df.iloc[3:5,0:2])

A    0.062134
B    0.066643
C   -0.580331
D    2.162716
Name: 2025-11-26 13:45:00, dtype: float64

                            A         B
2025-11-26 13:45:00  0.062134  0.066643
2025-11-26 14:45:00  1.105816  1.055264

In [29]:
# selecting raws 1,2 and 4 for columns 0 and 2
df.iloc[[1,2,4],[0,2]]

                            A         C
2025-11-26 11:45:00  1.654689 -0.895581
2025-11-26 12:45:00  1.886450  0.844874
2025-11-26 14:45:00  1.105816  0.541669

In [30]:
# slicing rows explicitly
print (df.iloc[1:3,:],'\n')

# slicing columns explicitly
print (df.iloc[:,1:3])

# selecting an individual element by position
print(df.iloc[1,1])

                            A         B         C         D
2025-11-26 11:45:00  1.654689  1.110970 -0.895581 -0.187253
2025-11-26 12:45:00  1.886450  2.539469  0.844874  0.479326

                            B         C
2025-11-26 10:45:00 -1.835610 -0.304355
2025-11-26 11:45:00  1.110970 -0.895581
2025-11-26 12:45:00  2.539469  0.844874
2025-11-26 13:45:00  0.066643 -0.580331
2025-11-26 14:45:00  1.055264  0.541669
2025-11-26 15:45:00  0.262217  1.154242
2025-11-26 16:45:00  0.163264  0.161566
2025-11-26 17:45:00 -0.111925 -0.926319
2025-11-26 18:45:00 -0.695074 -0.345806
2025-11-26 19:45:00 -0.023291  2.685807
1.1109703642315973

### Boolean index

Very powerful way of filtering out data with certain features. Notation is very similar to numpy arrays.

In [31]:
# Filter by a boolean condition on the values of a single column
df[df['B'] > 0]

                            A         B         C         D
2025-11-26 11:45:00  1.654689  1.110970 -0.895581 -0.187253
2025-11-26 12:45:00  1.886450  2.539469  0.844874  0.479326
2025-11-26 13:45:00  0.062134  0.066643 -0.580331  2.162716
2025-11-26 14:45:00  1.105816  1.055264  0.541669  1.183234
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  0.332705
2025-11-26 16:45:00 -1.113811  0.163264  0.161566 -0.770786

In [32]:
# Selecting on the basis of boolean conditions applied to the whole DataFrame
df[df>0]

# a DataFrame with the same shape is returned, with NaN's where condition is not met

                            A         B         C         D
2025-11-26 10:45:00       NaN       NaN       NaN       NaN
2025-11-26 11:45:00  1.654689  1.110970       NaN       NaN
2025-11-26 12:45:00  1.886450  2.539469  0.844874  0.479326
2025-11-26 13:45:00  0.062134  0.066643       NaN  2.162716
2025-11-26 14:45:00  1.105816  1.055264  0.541669  1.183234
2025-11-26 15:45:00       NaN  0.262217  1.154242  0.332705
2025-11-26 16:45:00       NaN  0.163264  0.161566       NaN
2025-11-26 17:45:00  0.533201       NaN       NaN       NaN
2025-11-26 18:45:00       NaN       NaN       NaN  0.684370
2025-11-26 19:45:00  2.188733       NaN  2.685807       NaN

### Setting

Combination of selection and setting of values

In [33]:
# setting values by label (same as by position)
df.at[dates[0],'A'] = 0

# setting and assigning a numpy array
df.loc[:,'D'] = np.array([5] * len(df)) # This is "len(df)" times the value 5.

# defining a brend new column
df['E'] = np.arange(len(df))*0.5

# defining a brend new column by means of a pd.Series: indexes must be the same!
df['E prime'] = pd.Series(np.arange(len(df))*2, index=df.index)

df

                            A         B         C    D    E  E prime
2025-11-26 10:45:00  0.000000 -1.835610 -0.304355  5.0  0.0        0
2025-11-26 11:45:00  1.654689  1.110970 -0.895581  5.0  0.5        2
2025-11-26 12:45:00  1.886450  2.539469  0.844874  5.0  1.0        4
2025-11-26 13:45:00  0.062134  0.066643 -0.580331  5.0  1.5        6
2025-11-26 14:45:00  1.105816  1.055264  0.541669  5.0  2.0        8
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  5.0  2.5       10
2025-11-26 16:45:00 -1.113811  0.163264  0.161566  5.0  3.0       12
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319  5.0  3.5       14
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806  5.0  4.0       16
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5       18

In [34]:
def dcos(theta):
    theta = theta*(np.pi/180)
    return np.cos(theta)
 
df['cosine'] = pd.Series(df["E"].apply(dcos), index=df.index)
df

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.835610 -0.304355  5.0  0.0        0  1.000000
2025-11-26 11:45:00  1.654689  1.110970 -0.895581  5.0  0.5        2  0.999962
2025-11-26 12:45:00  1.886450  2.539469  0.844874  5.0  1.0        4  0.999848
2025-11-26 13:45:00  0.062134  0.066643 -0.580331  5.0  1.5        6  0.999657
2025-11-26 14:45:00  1.105816  1.055264  0.541669  5.0  2.0        8  0.999391
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  5.0  2.5       10  0.999048
2025-11-26 16:45:00 -1.113811  0.163264  0.161566  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319  5.0  3.5       14  0.998135
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806  5.0  4.0       16  0.997564
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5       18  0.996917

In [35]:
# another example of global setting
df2=df.copy()

df2[df2>0] = -df2
df2

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.835610 -0.304355 -5.0  0.0        0 -1.000000
2025-11-26 11:45:00 -1.654689 -1.110970 -0.895581 -5.0 -0.5       -2 -0.999962
2025-11-26 12:45:00 -1.886450 -2.539469 -0.844874 -5.0 -1.0       -4 -0.999848
2025-11-26 13:45:00 -0.062134 -0.066643 -0.580331 -5.0 -1.5       -6 -0.999657
2025-11-26 14:45:00 -1.105816 -1.055264 -0.541669 -5.0 -2.0       -8 -0.999391
2025-11-26 15:45:00 -0.549717 -0.262217 -1.154242 -5.0 -2.5      -10 -0.999048
2025-11-26 16:45:00 -1.113811 -0.163264 -0.161566 -5.0 -3.0      -12 -0.998630
2025-11-26 17:45:00 -0.533201 -0.111925 -0.926319 -5.0 -3.5      -14 -0.998135
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806 -5.0 -4.0      -16 -0.997564
2025-11-26 19:45:00 -2.188733 -0.023291 -2.685807 -5.0 -4.5      -18 -0.996917

### Are you dealing with a Copy or a View?

In general is hard to tell..

In [40]:
dfd = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})

# This is likely a view
subset = dfd.loc[0:1, 'a']  
subset[0] = 100  # May affect `df`

print (dfd)

# This is a copy
subset = dfd.loc[[0, 1], 'a']  
subset[0] = 200  # Does NOT affect `df`

print (dfd)

     a  b
0  100  4
1    2  5
2    3  6
     a  b
0  100  4
1    2  5
2    3  6

The behaviour depend on the version of Pandas and on the version of Numpy that given version of Pandas depends upon. Since Pandas 1.5 "Copy-on-Write" (CoW) is (optionally) available and as of Pandas 3.0 will be the default. 

With CoW chained assignemt will never work; in the following example, the view `dfd["a"]` and `df` itself are modified in one step. This will lead to a `ChainedAssignemntError`

In [41]:
dfd["a"][dfd["b"] > 5] = 100
dfd

C:\Users\itter\AppData\Local\Temp\ipykernel_68816\449088826.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfd["a"][dfd["b"] > 5] = 100

     a  b
0  100  4
1    2  5
2  100  6

With copy on write this can be done by using `loc`

In [42]:
dfd.loc[dfd["b"] > 5, "a"] = 200
dfd

     a  b
0  100  4
1    2  5
2  200  6

### Dropping

N.B.: dropping doesn't act permanently on the DataFrame, i.e. to get that do :
```python
df = df.drop(....)
```

In [43]:
# Dropping by column
df.drop(['E prime'], axis=1)

#which is equivalent to
new_df=df.drop(columns=['E prime'])
new_df

                            A         B         C    D    E    cosine
2025-11-26 10:45:00  0.000000 -1.835610 -0.304355  5.0  0.0  1.000000
2025-11-26 11:45:00  1.654689  1.110970 -0.895581  5.0  0.5  0.999962
2025-11-26 12:45:00  1.886450  2.539469  0.844874  5.0  1.0  0.999848
2025-11-26 13:45:00  0.062134  0.066643 -0.580331  5.0  1.5  0.999657
2025-11-26 14:45:00  1.105816  1.055264  0.541669  5.0  2.0  0.999391
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  5.0  2.5  0.999048
2025-11-26 16:45:00 -1.113811  0.163264  0.161566  5.0  3.0  0.998630
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319  5.0  3.5  0.998135
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806  5.0  4.0  0.997564
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5  0.996917

In [44]:
# Dropping by raws
# safe and always working
df.drop(df.index[[1,2,3,4]])

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.835610 -0.304355  5.0  0.0        0  1.000000
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  5.0  2.5       10  0.999048
2025-11-26 16:45:00 -1.113811  0.163264  0.161566  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319  5.0  3.5       14  0.998135
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806  5.0  4.0       16  0.997564
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5       18  0.996917

In [45]:
df

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.835610 -0.304355  5.0  0.0        0  1.000000
2025-11-26 11:45:00  1.654689  1.110970 -0.895581  5.0  0.5        2  0.999962
2025-11-26 12:45:00  1.886450  2.539469  0.844874  5.0  1.0        4  0.999848
2025-11-26 13:45:00  0.062134  0.066643 -0.580331  5.0  1.5        6  0.999657
2025-11-26 14:45:00  1.105816  1.055264  0.541669  5.0  2.0        8  0.999391
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  5.0  2.5       10  0.999048
2025-11-26 16:45:00 -1.113811  0.163264  0.161566  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319  5.0  3.5       14  0.998135
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806  5.0  4.0       16  0.997564
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5       18  0.996917

In [46]:
# something like df.drop('index_name') 
# would work but the type of index must be specificed, 
# in particular with DatetimeIndex
df.drop(pd.to_datetime("2025-11-26 18:45:00"))

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.835610 -0.304355  5.0  0.0        0  1.000000
2025-11-26 11:45:00  1.654689  1.110970 -0.895581  5.0  0.5        2  0.999962
2025-11-26 12:45:00  1.886450  2.539469  0.844874  5.0  1.0        4  0.999848
2025-11-26 13:45:00  0.062134  0.066643 -0.580331  5.0  1.5        6  0.999657
2025-11-26 14:45:00  1.105816  1.055264  0.541669  5.0  2.0        8  0.999391
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  5.0  2.5       10  0.999048
2025-11-26 16:45:00 -1.113811  0.163264  0.161566  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319  5.0  3.5       14  0.998135
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5       18  0.996917

## Missing data

pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations.

In [47]:
df_wNan = df[df>-0.5]
df_wNan

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000       NaN -0.304355  5.0  0.0        0  1.000000
2025-11-26 11:45:00  1.654689  1.110970       NaN  5.0  0.5        2  0.999962
2025-11-26 12:45:00  1.886450  2.539469  0.844874  5.0  1.0        4  0.999848
2025-11-26 13:45:00  0.062134  0.066643       NaN  5.0  1.5        6  0.999657
2025-11-26 14:45:00  1.105816  1.055264  0.541669  5.0  2.0        8  0.999391
2025-11-26 15:45:00       NaN  0.262217  1.154242  5.0  2.5       10  0.999048
2025-11-26 16:45:00       NaN  0.163264  0.161566  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.533201 -0.111925       NaN  5.0  3.5       14  0.998135
2025-11-26 18:45:00       NaN       NaN -0.345806  5.0  4.0       16  0.997564
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5       18  0.996917

In [66]:
# dropping raws with at least a Nan
df_wNan.dropna(how='any',axis=0) # We can also use 'all' to drop raws with all Nan. 'axis=0' are asigned by default.

                            A         B         C    D    E  E prime    cosine
2025-11-26 12:45:00  1.886450  2.539469  0.844874  5.0  1.0        4  0.999848
2025-11-26 14:45:00  1.105816  1.055264  0.541669  5.0  2.0        8  0.999391
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5       18  0.996917

In [67]:
# getting a mask
df_wNan.isna()
#df_wNan.notna()

                         A      B      C      D      E  E prime  cosine
2025-11-26 10:45:00  False   True  False  False  False    False   False
2025-11-26 11:45:00  False  False   True  False  False    False   False
2025-11-26 12:45:00  False  False  False  False  False    False   False
2025-11-26 13:45:00  False  False   True  False  False    False   False
2025-11-26 14:45:00  False  False  False  False  False    False   False
2025-11-26 15:45:00   True  False  False  False  False    False   False
2025-11-26 16:45:00   True  False  False  False  False    False   False
2025-11-26 17:45:00  False  False   True  False  False    False   False
2025-11-26 18:45:00   True   True  False  False  False    False   False
2025-11-26 19:45:00  False  False  False  False  False    False   False

In [68]:
# filling missing data
df_wNan.fillna(value=0)

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000  0.000000 -0.304355  5.0  0.0        0  1.000000
2025-11-26 11:45:00  1.654689  1.110970  0.000000  5.0  0.5        2  0.999962
2025-11-26 12:45:00  1.886450  2.539469  0.844874  5.0  1.0        4  0.999848
2025-11-26 13:45:00  0.062134  0.066643  0.000000  5.0  1.5        6  0.999657
2025-11-26 14:45:00  1.105816  1.055264  0.541669  5.0  2.0        8  0.999391
2025-11-26 15:45:00  0.000000  0.262217  1.154242  5.0  2.5       10  0.999048
2025-11-26 16:45:00  0.000000  0.163264  0.161566  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.533201 -0.111925  0.000000  5.0  3.5       14  0.998135
2025-11-26 18:45:00  0.000000  0.000000 -0.345806  5.0  4.0       16  0.997564
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5       18  0.996917

Fill gaps forward or backward by propagating non-NA values forward or backward:

In [72]:
df_wNan.ffill()
# df_wNan.bfill()

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000       NaN -0.304355  5.0  0.0        0  1.000000
2025-11-26 11:45:00  1.654689  1.110970 -0.304355  5.0  0.5        2  0.999962
2025-11-26 12:45:00  1.886450  2.539469  0.844874  5.0  1.0        4  0.999848
2025-11-26 13:45:00  0.062134  0.066643  0.844874  5.0  1.5        6  0.999657
2025-11-26 14:45:00  1.105816  1.055264  0.541669  5.0  2.0        8  0.999391
2025-11-26 15:45:00  1.105816  0.262217  1.154242  5.0  2.5       10  0.999048
2025-11-26 16:45:00  1.105816  0.163264  0.161566  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.533201 -0.111925  0.161566  5.0  3.5       14  0.998135
2025-11-26 18:45:00  0.533201 -0.111925 -0.345806  5.0  4.0       16  0.997564
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5       18  0.996917

## Operations

Here comes the most relevant advantage of DataFrame. Operations on columns are extremly fast due to several intrinsic optimizations:

* They are implemented in C/Cython via NumPy.
* Pandas processes columns as contiguous memory arrays.
* Vectorized operations eliminate the need for slow Python loops.
* Efficient memory and cache utilization boost performance.

In [73]:
# Some statistics (mean() just as an example)
# raws
print (df.mean(axis=0),'\n')
# columns
print (df.mean(axis=1),'\n')

A          0.375881
B          0.253193
C          0.233576
D          5.000000
E          2.250000
E prime    9.000000
cosine     0.998915
dtype: float64

2025-11-26 10:45:00    0.551434
2025-11-26 11:45:00    1.481434
2025-11-26 12:45:00    2.324377
2025-11-26 13:45:00    1.864015
2025-11-26 14:45:00    2.671734
2025-11-26 15:45:00    2.766541
2025-11-26 16:45:00    2.887093
2025-11-26 17:45:00    3.284727
2025-11-26 18:45:00    3.278285
2025-11-26 19:45:00    4.764024
Freq: h, dtype: float64

In [74]:
# global operations on columns
df.apply(np.cumsum)

,A,B,C,D,E,E prime,cosine
2025-11-26 10:45:00,0.000000,-1.835610,-0.304355,5.0,0.0,0,1.000000
2025-11-26 11:45:00,1.654689,-0.724639,-1.199937,10.0,0.5,2,1.999962
2025-11-26 12:45:00,3.541139,1.814829,-0.355063,15.0,1.5,6,2.999810
2025-11-26 13:45:00,3.603273,1.881473,-0.935394,20.0,3.0,12,3.999467
2025-11-26 14:45:00,4.709089,2.936737,-0.393725,25.0,5.0,20,4.998858
2025-11-26 15:45:00,4.159371,3.198953,0.760517,30.0,7.5,30,5.997906
2025-11-26 16:45:00,3.045561,3.362218,0.922083,35.0,10.5,42,6.996536
2025-11-26 17:45:00,3.578762,3.250293,-0.004236,40.0,14.0,56,7.994670
2025-11-26 18:45:00,1.570074,2.555219,-0.350043,45.0,18.0,72,8.992234
2025-11-26 19:45:00,3.758807,2.531928,2.335764,50.0,22.5,90,9.989152

In [75]:
df

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -1.835610 -0.304355  5.0  0.0        0  1.000000
2025-11-26 11:45:00  1.654689  1.110970 -0.895581  5.0  0.5        2  0.999962
2025-11-26 12:45:00  1.886450  2.539469  0.844874  5.0  1.0        4  0.999848
2025-11-26 13:45:00  0.062134  0.066643 -0.580331  5.0  1.5        6  0.999657
2025-11-26 14:45:00  1.105816  1.055264  0.541669  5.0  2.0        8  0.999391
2025-11-26 15:45:00 -0.549717  0.262217  1.154242  5.0  2.5       10  0.999048
2025-11-26 16:45:00 -1.113811  0.163264  0.161566  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.533201 -0.111925 -0.926319  5.0  3.5       14  0.998135
2025-11-26 18:45:00 -2.008688 -0.695074 -0.345806  5.0  4.0       16  0.997564
2025-11-26 19:45:00  2.188733 -0.023291  2.685807  5.0  4.5       18  0.996917

In [76]:
df.apply(lambda x: x.max() - x.min())

A           4.197420
B           4.375079
C           3.612126
D           0.000000
E           4.500000
E prime    18.000000
cosine      0.003083
dtype: float64

In [77]:
# syntax is as usual similar to that of numpy arrays
df['A']+df['B']

2025-11-26 10:45:00   -1.835610
2025-11-26 11:45:00    2.765659
2025-11-26 12:45:00    4.425919
2025-11-26 13:45:00    0.128777
2025-11-26 14:45:00    2.161080
2025-11-26 15:45:00   -0.287501
2025-11-26 16:45:00   -0.950546
2025-11-26 17:45:00    0.421276
2025-11-26 18:45:00   -2.703762
2025-11-26 19:45:00    2.165441
Freq: h, dtype: float64

Let's play it hard and load (in memory) a (relatively) large dataset

In [85]:
# WARNING! link in past notebook was wrong!, (if needed) get the right file from:
#!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt -P ~/data/

file_name="/Users/itter/UNIPD 1st year programming/LaboratoryOfComputationalPhysics_Y8//data/data_000637.txt"
data=pd.read_csv(file_name)
data.tail(10)

         HEAD  FPGA  TDC_CHANNEL   ORBIT_CNT  BX_COUNTER  TDC_MEAS
1310710     1     1           36  3869211171         427        13
1310711     1     1           39  3869211171         430         0
1310712     1     1           35  3869211171         429         4
1310713     1     0           64  3869211171         758        18
1310714     1     0           60  3869211171         762         2
1310715     1     0           62  3869211171         762        14
1310716     1     1            4  3869211171         763        11
1310717     1     0           64  3869211171         764         0
1310718     1     0          139  3869211171         769         0
1310719     1     0           61  3869211171         762        18

Let's now do some operations among (elements of) columns

In [79]:
# the one-liner killing it all
data['timens']=data['TDC_MEAS']*25/30+data['BX_COUNTER']*25

NameError: name 'data' is not defined

In [80]:
data['timens']

NameError: name 'data' is not defined

In [81]:
# the old slooow way
def conversion(data):
    result=[]
    for i in range(len(data)): 
        result.append(data.loc[data.index[i],'TDC_MEAS']*25/30.+data.loc[data.index[i],'BX_COUNTER']*25)
    return result

data['timens']=conversion(data)

NameError: name 'data' is not defined

For tasks on extremely large datasets, libraries like [Polars](https://docs.pola.rs) or [Dask](https://www.dask.org) can offer even faster alternatives by further parallelizing or optimizing columnar operations.

## Merge

pandas provides various facilities for easily combining together Series, DataFrame, and Panel objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

### Concat

concatenation (adding rows) is straightforward

In [ ]:
rdf = pd.DataFrame(np.random.randn(10, 4))
rdf

In [ ]:
# divide it into pieaces raw-wise
pieces = [rdf[:3], rdf[3:7], rdf[7:]]
pieces

In [ ]:
# put it back together
#pd.concat(pieces)

# indexes can be ignored
pd.concat(pieces, ignore_index=True)

# in case of dimension mismatch, Nan are added where needed

In [ ]:
# appending a single row (as a Series)
s = rdf.iloc[3]
rdf = pd.concat([rdf,s.to_frame().T], ignore_index=True)
rdf

### Merge/Join

SQL like operations on table can be performed on DataFrames. This is all rather sophisticated, refer to the [doc](https://pandas.pydata.org/pandas-docs/stable/merging.html#merging) for more info/examples.

#### Merging, Inner Join (default)

Only rows with matching id values are included:

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'id': [2, 3, 4], 'age': [25, 30, 35]})

# Merge on the 'id' column
result = pd.merge(df1, df2, on='id')
print(result)

#### Merging, Left Join

A left join includes all rows from `df1` (left) and fills in `NaN` for missing matches in `df2`.

In [ ]:
result = pd.merge(df2, df1, on='id', how='left')
print(result)

#### Merging, Outer Join

An outer join includes all rows from both DataFrames, filling NaN for missing values

In [ ]:
result = pd.merge(df1, df2, on='id', how='outer')
print(result)

`join` is similar to `merge` but uses index as key and has 'Left' as default

In [ ]:
df1 = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie']}, index=[1, 2, 3])
df2 = pd.DataFrame({'age': [25, 30, 35]}, index=[2, 3, 4])

result = df1.join(df2)
print(result)

## Grouping

By “group by” we are referring to a process involving one or more of the following steps:

* Splitting the data into groups based on some criteria
* Applying a function to each group independently
* Combining the results into a data structure


Grouping is one of the most powerful and at the same time most sofisticated action you can perform with DataFrames. Mastering it is key for an effective usage of Pandas and vectorized data analysis. Reading the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html) or going through a [tutorial](https://realpython.com/pandas-groupby/) is warmly recommended. 

Let's go through a few examples:

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C'],
    'Values': [10, 20, 30, 40, 50, 60]
}

df = pd.DataFrame(data)

# Group by 'Category' and calculate the sum
result = df.groupby('Category').sum()
print(result)

In [ ]:
# Multiple Aggregations
result = df.groupby('Category').agg(['sum', 'mean'])
print(result)

In [ ]:
# Grouping by multiple columns
df = pd.DataFrame({'Category': ['A', 'A', 'B', 'B', 'C', 'C'],
                   'Type': ['X', 'Y', 'X', 'Y', 'X', 'Y'],
                   'Values': [10, 20, 30, 40, 50, 60]})

result = df.groupby(['Category', 'Type']).sum()
print(result)

In [ ]:
# Trasformations using groupby(): add group averages to DataFrame
df['Group_Avg'] = df.groupby('Category')['Values'].transform('mean')
print(df)

In [ ]:
# filtering
filtered = df.groupby('Category').filter(lambda x: x['Values'].sum() > 50)
print(filtered)

In [ ]:
# custom aggregation with apply()
def custom_aggregation(group):
    return pd.Series({
        'Sum': group['Values'].sum(),
        'Max': group['Values'].max(),
        'Count': group['Values'].count()
    })

result = df.groupby('Category').apply(custom_aggregation)
print(result)

In [ ]:
# splitting data into groups
grouped = df.groupby('Category')

for name, group in grouped:
    print(f"Group: {name}")
    print(group)

## Multi-indexing


Hierarchical / Multi-level indexing allows sophisticated data analysis on higher dimensional data. In essence, it enables you to store and manipulate data with an arbitrary number of dimensions in lower dimensional data structures like Series (1d) and DataFrame (2d).

In [ ]:
tuples = list(zip(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']))
multi_index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
print (multi_index,'\n')

s = pd.Series(np.random.randn(8), index=multi_index)
print (s)

In [ ]:
gdf = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar', 'foo', 'foo'],
                    'B' : ['one', 'one', 'two', 'three',
                           'two', 'two', 'one', 'three'],
                    'C' : np.random.randn(8),
                    'D' : np.random.randn(8)})
gdf

# it enables further features of the groupby method,
# e.g. when group-by by multiple columns
gdf.groupby(['A','B']).sum()

In [ ]:
# stack() method “compresses” a level in the DataFrame’s columns
gdf.groupby(['A','B']).sum().stack()

## Plotting

Just a preview, more on the next lab class!

In [ ]:
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts.cumsum().plot()

In [ ]:
import matplotlib.pyplot as plt

pdf=pd.DataFrame(np.random.randn(1000, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
pdf = pdf.cumsum()
plt.figure(); pdf.plot(); plt.legend(loc='best')