# Pandas

The `numpy` module is excellent for numerical computations, but to handle missing data or arrays with mixed types takes more work. The `pandas` module is currently the most widely used tool for data manipulation, providing high-performance, easy-to-use data structures and advanced data analysis tools.

In particular `pandas` features:

* A fast and efficient "DataFrame" object for data manipulation with integrated indexing;
* Tools for reading and writing data between in-memory data structures and different formats (CSV, Excel, SQL, HDF5);
* Intelligent data alignment and integrated handling of missing data;
* Intelligent label-based slicing, fancy indexing, and subsetting of large data sets;
* Aggregating or transforming data with a powerful "group-by" engine; 
* High performance merging and joining of data sets;
* Hierarchical axis indexing provides an intuitive way of working with high-dimensional data in a lower-dimensional data structure;
* Time series-functionalities;
* Highly optimized for performance, with critical code paths written in Cython or C.

In [1]:
import pandas as pd
import numpy as np

## Series

Series are completely equivalent to 1D array but with axis labels and the possibility to store heterogeneous elements. Of paramount importance are the time-series, used to define time evolutions of a phenomenon.

In [2]:
from string import ascii_lowercase as letters

# Creating a series, accessing indexes, values and values by their index 
xs = pd.Series(np.arange(10)*0.5, index=tuple(letters[:10]))
print ("xs:", xs,'\n')
print ("xs indexes:",xs.index,'\n')
# Values of the Series are actually a numpy array
print ("xs values:", xs.values, type(xs.values),'\n')
print (xs['f'], xs.f, xs.h, '\n')
print (xs[['d', 'f', 'h']], '\n')
print (type(xs[['d', 'f', 'h']]), '\n')

xs: a    0.0
b    0.5
c    1.0
d    1.5
e    2.0
f    2.5
g    3.0
h    3.5
i    4.0
j    4.5
dtype: float64

xs indexes: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

xs values: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5] <class 'numpy.ndarray'>

2.5 2.5 3.5

d    1.5
f    2.5
h    3.5
dtype: float64

<class 'pandas.core.series.Series'>

In [3]:
# Extracting elements and operations: same as numpy array
print (xs[:3],'\n')
print (xs[7:], '\n')
print (xs[::3], '\n')
print (xs[xs>3], '\n')
print (np.exp(xs), '\n')
print (np.mean(xs), np.std(xs), '\n')

a    0.0
b    0.5
c    1.0
dtype: float64

h    3.5
i    4.0
j    4.5
dtype: float64

a    0.0
d    1.5
g    3.0
j    4.5
dtype: float64

h    3.5
i    4.0
j    4.5
dtype: float64

a     1.000000
b     1.648721
c     2.718282
d     4.481689
e     7.389056
f    12.182494
g    20.085537
h    33.115452
i    54.598150
j    90.017131
dtype: float64

2.25 1.4361406616345072

In [6]:
# Series can be created from python dictionary too.
# Notice that the elements can be whatever!
d = {'b' : 1, 'a' : 'cat', 'c' : [2,3]}
pd.Series(d)

b         1
a       cat
c    [2, 3]
dtype: object

A key difference between Series and nparray is that operations between Series automatically align the data based on label. Thus, you can write computations without considering whether the Series involved have the same labels.

In [12]:
s = pd.Series(np.random.randn(5), index=tuple(letters[:5]))
print(s)
s = s[1:] + s[:-1]
print(s)

a    2.224631
b   -0.594169
c    0.124932
d    1.648767
e    1.991744
dtype: float64
a         NaN
b   -1.188337
c    0.249863
d    3.297535
e         NaN
dtype: float64

### Time series

Time series are very often used to profile the behaviour of a quantity as a function of time. Pandas has a special index for that, `DatetimeIndex`, that can be created e.g. with the function `pd.data_range()`

In [33]:
# to define a date, the datetime module is very useful
import datetime as dt
date = dt.date.today()
print(date)

date = dt.datetime(2025,11,26,10,45,10,15)
print (date)

# otherwise, several notations are interpreted too
date = 'Nov 26 2025'
# or alternatively
#date = '26/11/2025 10:45:00'
print (date)

days2 = pd.date_range(date, periods=7, freq='2D') # Create 7 consecutive dates starting from `date`, one each 2 days (D = daily).
print (days2)

seconds = pd.date_range(date, periods=3600, freq='s')
print (seconds)

2025-12-25
2025-11-26 10:45:10.000015
Nov 26 2025
DatetimeIndex(['2025-11-26', '2025-11-28', '2025-11-30', '2025-12-02',
               '2025-12-04', '2025-12-06', '2025-12-08'],
              dtype='datetime64[ns]', freq='2D')
DatetimeIndex(['2025-11-26 00:00:00', '2025-11-26 00:00:01',
               '2025-11-26 00:00:02', '2025-11-26 00:00:03',
               '2025-11-26 00:00:04', '2025-11-26 00:00:05',
               '2025-11-26 00:00:06', '2025-11-26 00:00:07',
               '2025-11-26 00:00:08', '2025-11-26 00:00:09',
               ...
               '2025-11-26 00:59:50', '2025-11-26 00:59:51',
               '2025-11-26 00:59:52', '2025-11-26 00:59:53',
               '2025-11-26 00:59:54', '2025-11-26 00:59:55',
               '2025-11-26 00:59:56', '2025-11-26 00:59:57',
               '2025-11-26 00:59:58', '2025-11-26 00:59:59'],
              dtype='datetime64[ns]', length=3600, freq='s')

To learn more about the frequency strings, please see this [link](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#offset-aliases)


Timestamped data is the most basic type of time series data that associates values with points in time. For pandas objects it means using the points in time.

functions like `pd.to_datetime` can be used, for instance, when reading information as string from a dataset.

Timestamp is the pandas equivalent of python’s Datetime and is interchangeable with it in most cases.

In [29]:
tstamp = pd.Timestamp(dt.datetime(2020, 11, 9))

# internally it counts the nanoseconds from January 1st 1970
# tstamp = pd.Timestamp(dt.datetime(1970, 1, 1, 0, 0, 0, 1)) # Last value is for microseconds.
print(tstamp.value) # Notice that `.value` gives the integer (nanoseconds since 1970-01-01 UTC) used internally to store the Timestamp.

# when creating a timestamp the format can be explicitly passed
ts = pd.to_datetime('2010/11/12', format='%Y/%m/%d')
print (type(ts))
print (ts.value)
ts = pd.to_datetime('12-11-2010 00:00', format='%d-%m-%Y %H:%M')
print (ts)
print (ts.value)

1604880000000000000
<class 'pandas._libs.tslibs.timestamps.Timestamp'>
1289520000000000000
2010-11-12 00:00:00
1289520000000000000

A standard series can be created and (range of) elements can be used as indexes

In [43]:
tseries = pd.Series(np.random.normal(10, 1, len(days2)), index=days2)
# Extracting elements
print (tseries[0:4], '\n')
print (tseries['2025-11-26':'2025-12-02'], '\n') # Note - includes end time

2025-11-26    10.843858
2025-11-28     9.286747
2025-11-30     7.965861
2025-12-02     9.818586
Freq: 2D, dtype: float64

2025-11-26    10.843858
2025-11-28     9.286747
2025-11-30     7.965861
2025-12-02     9.818586
Freq: 2D, dtype: float64

`pd.to_datetime` can also be used to create a `DatetimeIndex`:

In [44]:
pd.to_datetime([1, 2, 3, 4], unit='D', origin=pd.Timestamp('1980-02-03'))

DatetimeIndex(['1980-02-04', '1980-02-05', '1980-02-06', '1980-02-07'], dtype='datetime64[ns]', freq=None)

## DataFrame

A pandas DataFrame is like a simple tabular spreadsheet. For future reference (or for people already familiar with R), a pandas DataFrame is very similar to the R DataFrame.

Each column in a DataFrame is a Series object.

The element can be whatever, missing data is also treated (as NaN)

### DataFrame creation

A DataFrame can be created implicitly, with, e.g., a DatatimeIndex object as index:

In [45]:
entries=10
dates=pd.date_range('11/26/2025 10:45:00',freq='h', periods=entries)
df = pd.DataFrame(np.random.randn(entries,4), index=dates, columns=['A','B','C','D'])
df

                            A         B         C         D
2025-11-26 10:45:00 -0.177842 -0.471869  0.511453  1.051404
2025-11-26 11:45:00  1.265489  0.531300 -0.667643 -0.775615
2025-11-26 12:45:00 -0.870895  0.820787 -0.153566 -1.583983
2025-11-26 13:45:00  0.910680 -1.195849  0.302311  1.378908
2025-11-26 14:45:00 -0.532654 -1.100528 -1.461212  1.188936
2025-11-26 15:45:00  1.678756 -0.231858 -0.104664  0.588048
2025-11-26 16:45:00  0.520450  0.444356  0.077013  0.345359
2025-11-26 17:45:00  0.028137  1.652969 -1.822554  0.579359
2025-11-26 18:45:00  0.624245  0.716090  1.301692 -0.549737
2025-11-26 19:45:00  0.244254  0.544641  0.827383 -0.450897

or by means of a dictionary:

In [57]:
df2 = pd.DataFrame(
    { 'A' : 1.,
      'B' : pd.Timestamp('20130102'),
      'C' : pd.Series(1,index=range(4),dtype='float32'),
      'D' : np.arange(7,11),
      'E' : pd.Categorical(["test","train","test","train"]),
    }
    )
df2

# All arrays must be of the same length.
# "pd.Categorical" is a pandas type for data with a limited set of discrete values (e.g., "test"/"train").

     A          B    C   D      E
0  1.0 2013-01-02  1.0   7   test
1  1.0 2013-01-02  1.0   8  train
2  1.0 2013-01-02  1.0   9   test
3  1.0 2013-01-02  1.0  10  train

### Viewing Data

In [58]:
df.head(2)

                            A         B         C         D
2025-11-26 10:45:00 -0.177842 -0.471869  0.511453  1.051404
2025-11-26 11:45:00  1.265489  0.531300 -0.667643 -0.775615

In [59]:
df.tail(4)

                            A         B         C         D
2025-11-26 16:45:00  0.520450  0.444356  0.077013  0.345359
2025-11-26 17:45:00  0.028137  1.652969 -1.822554  0.579359
2025-11-26 18:45:00  0.624245  0.716090  1.301692 -0.549737
2025-11-26 19:45:00  0.244254  0.544641  0.827383 -0.450897

In [60]:
df.index

DatetimeIndex(['2025-11-26 10:45:00', '2025-11-26 11:45:00',
               '2025-11-26 12:45:00', '2025-11-26 13:45:00',
               '2025-11-26 14:45:00', '2025-11-26 15:45:00',
               '2025-11-26 16:45:00', '2025-11-26 17:45:00',
               '2025-11-26 18:45:00', '2025-11-26 19:45:00'],
              dtype='datetime64[ns]', freq='h')

In [61]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [62]:
df.values

array([[-0.17784177, -0.471869  ,  0.51145323,  1.0514035 ],
       [ 1.26548908,  0.53130005, -0.66764281, -0.77561541],
       [-0.87089506,  0.82078735, -0.15356599, -1.58398304],
       [ 0.91067952, -1.19584934,  0.30231076,  1.37890781],
       [-0.53265384, -1.10052829, -1.46121216,  1.18893601],
       [ 1.67875583, -0.23185759, -0.10466387,  0.58804797],
       [ 0.52045039,  0.44435551,  0.07701345,  0.34535857],
       [ 0.02813724,  1.65296942, -1.82255425,  0.57935864],
       [ 0.62424462,  0.71608993,  1.30169174, -0.5497372 ],
       [ 0.24425432,  0.54464109,  0.82738347, -0.45089707]])

In [63]:
df.describe()

               A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean    0.369062   0.171004  -0.118979   0.177178
std     0.794548   0.901872   0.973735   0.973157
min    -0.870895  -1.195849  -1.822554  -1.583983
25%    -0.126347  -0.411866  -0.539124  -0.525027
50%     0.382352   0.487828  -0.013825   0.462359
75%     0.839071   0.673228   0.459168   0.935565
max     1.678756   1.652969   1.301692   1.378908

In [64]:
df.T

,2025-11-26 10:45:00,2025-11-26 11:45:00,2025-11-26 12:45:00,2025-11-26 13:45:00,2025-11-26 14:45:00,2025-11-26 15:45:00,2025-11-26 16:45:00,2025-11-26 17:45:00,2025-11-26 18:45:00,2025-11-26 19:45:00
A,-0.177842,1.265489,-0.870895,0.910680,-0.532654,1.678756,0.520450,0.028137,0.624245,0.244254
B,-0.471869,0.531300,0.820787,-1.195849,-1.100528,-0.231858,0.444356,1.652969,0.716090,0.544641
C,0.511453,-0.667643,-0.153566,0.302311,-1.461212,-0.104664,0.077013,-1.822554,1.301692,0.827383
D,1.051404,-0.775615,-1.583983,1.378908,1.188936,0.588048,0.345359,0.579359,-0.549737,-0.450897

In [82]:
df.sort_index(axis=0,ascending=False) # "axis = 1" changes the columns.

                            A         B         C         D
2025-11-26 19:45:00  0.244254  0.544641  0.827383 -0.450897
2025-11-26 18:45:00  0.624245  0.716090  1.301692 -0.549737
2025-11-26 17:45:00  0.028137  1.652969 -1.822554  0.579359
2025-11-26 16:45:00  0.520450  0.444356  0.077013  0.345359
2025-11-26 15:45:00  1.678756 -0.231858 -0.104664  0.588048
2025-11-26 14:45:00 -0.532654 -1.100528 -1.461212  1.188936
2025-11-26 13:45:00  0.910680 -1.195849  0.302311  1.378908
2025-11-26 12:45:00 -0.870895  0.820787 -0.153566 -1.583983
2025-11-26 11:45:00  1.265489  0.531300 -0.667643 -0.775615
2025-11-26 10:45:00 -0.177842 -0.471869  0.511453  1.051404

In [80]:
df.sort_values(by="C") # Sorts the rows of the DataFrame df based on the values in column "C", in ascending order by default.

                            A         B         C         D
2025-11-26 17:45:00  0.028137  1.652969 -1.822554  0.579359
2025-11-26 14:45:00 -0.532654 -1.100528 -1.461212  1.188936
2025-11-26 11:45:00  1.265489  0.531300 -0.667643 -0.775615
2025-11-26 12:45:00 -0.870895  0.820787 -0.153566 -1.583983
2025-11-26 15:45:00  1.678756 -0.231858 -0.104664  0.588048
2025-11-26 16:45:00  0.520450  0.444356  0.077013  0.345359
2025-11-26 13:45:00  0.910680 -1.195849  0.302311  1.378908
2025-11-26 10:45:00 -0.177842 -0.471869  0.511453  1.051404
2025-11-26 19:45:00  0.244254  0.544641  0.827383 -0.450897
2025-11-26 18:45:00  0.624245  0.716090  1.301692 -0.549737

## Selection

### Getting slices

The following show how to get part of the DataFrame (i.e. not just the elements)

In [83]:
## standard and safe
print (df['A'],'\n')

## equivalent but dangerous [imagine blank spaces in the name of the column (as A B for example)].
print (df.A)

2025-11-26 10:45:00   -0.177842
2025-11-26 11:45:00    1.265489
2025-11-26 12:45:00   -0.870895
2025-11-26 13:45:00    0.910680
2025-11-26 14:45:00   -0.532654
2025-11-26 15:45:00    1.678756
2025-11-26 16:45:00    0.520450
2025-11-26 17:45:00    0.028137
2025-11-26 18:45:00    0.624245
2025-11-26 19:45:00    0.244254
Freq: h, Name: A, dtype: float64

2025-11-26 10:45:00   -0.177842
2025-11-26 11:45:00    1.265489
2025-11-26 12:45:00   -0.870895
2025-11-26 13:45:00    0.910680
2025-11-26 14:45:00   -0.532654
2025-11-26 15:45:00    1.678756
2025-11-26 16:45:00    0.520450
2025-11-26 17:45:00    0.028137
2025-11-26 18:45:00    0.624245
2025-11-26 19:45:00    0.244254
Freq: h, Name: A, dtype: float64

In [84]:
# selecting rows by counting
print (df[0:3])

# or by index
print (df["2025-11-26 10:45:00":"2025-11-26 12:45:00"])

                            A         B         C         D
2025-11-26 10:45:00 -0.177842 -0.471869  0.511453  1.051404
2025-11-26 11:45:00  1.265489  0.531300 -0.667643 -0.775615
2025-11-26 12:45:00 -0.870895  0.820787 -0.153566 -1.583983
                            A         B         C         D
2025-11-26 10:45:00 -0.177842 -0.471869  0.511453  1.051404
2025-11-26 11:45:00  1.265489  0.531300 -0.667643 -0.775615
2025-11-26 12:45:00 -0.870895  0.820787 -0.153566 -1.583983

### Selection by label

In [85]:
# getting a cross section (part of the DataFrame) using a label
df.loc[dates[0]]

A   -0.177842
B   -0.471869
C    0.511453
D    1.051404
Name: 2025-11-26 10:45:00, dtype: float64

In [86]:
# selecting on a multi-axis by label:
df.loc[:,['A','B']]
#a=df.loc[:,['A','B']]

                            A         B
2025-11-26 10:45:00 -0.177842 -0.471869
2025-11-26 11:45:00  1.265489  0.531300
2025-11-26 12:45:00 -0.870895  0.820787
2025-11-26 13:45:00  0.910680 -1.195849
2025-11-26 14:45:00 -0.532654 -1.100528
2025-11-26 15:45:00  1.678756 -0.231858
2025-11-26 16:45:00  0.520450  0.444356
2025-11-26 17:45:00  0.028137  1.652969
2025-11-26 18:45:00  0.624245  0.716090
2025-11-26 19:45:00  0.244254  0.544641

In [87]:
# showing label slicing, both endpoints are included:
df.loc['2025-11-26 14:45:00':'2025-11-26 16:45:00',['A','B']]

                            A         B
2025-11-26 14:45:00 -0.532654 -1.100528
2025-11-26 15:45:00  1.678756 -0.231858
2025-11-26 16:45:00  0.520450  0.444356

In [88]:
# getting an individual element
print (df.loc[dates[1],'A'])

# equivalently
print (df.at[dates[1],'A'])

1.2654890786440705
1.2654890786440705

### Selecting by position

In [89]:
# select via the position of the passed integers:
print (df.iloc[3],'\n')

# notation similar to numpy/python
print (df.iloc[3:5,0:2])

A    0.910680
B   -1.195849
C    0.302311
D    1.378908
Name: 2025-11-26 13:45:00, dtype: float64

                            A         B
2025-11-26 13:45:00  0.910680 -1.195849
2025-11-26 14:45:00 -0.532654 -1.100528

In [90]:
# selecting raws 1,2 and 4 for columns 0 and 2
df.iloc[[1,2,4],[0,2]]

                            A         C
2025-11-26 11:45:00  1.265489 -0.667643
2025-11-26 12:45:00 -0.870895 -0.153566
2025-11-26 14:45:00 -0.532654 -1.461212

In [91]:
# slicing rows explicitly
print (df.iloc[1:3,:],'\n')

# slicing columns explicitly
print (df.iloc[:,1:3])

# selecting an individual element by position
print(df.iloc[1,1])

                            A         B         C         D
2025-11-26 11:45:00  1.265489  0.531300 -0.667643 -0.775615
2025-11-26 12:45:00 -0.870895  0.820787 -0.153566 -1.583983

                            B         C
2025-11-26 10:45:00 -0.471869  0.511453
2025-11-26 11:45:00  0.531300 -0.667643
2025-11-26 12:45:00  0.820787 -0.153566
2025-11-26 13:45:00 -1.195849  0.302311
2025-11-26 14:45:00 -1.100528 -1.461212
2025-11-26 15:45:00 -0.231858 -0.104664
2025-11-26 16:45:00  0.444356  0.077013
2025-11-26 17:45:00  1.652969 -1.822554
2025-11-26 18:45:00  0.716090  1.301692
2025-11-26 19:45:00  0.544641  0.827383
0.5313000490465142

### Boolean index

Very powerful way of filtering out data with certain features. Notation is very similar to numpy arrays.

In [92]:
# Filter by a boolean condition on the values of a single column
df[df['B'] > 0]

                            A         B         C         D
2025-11-26 11:45:00  1.265489  0.531300 -0.667643 -0.775615
2025-11-26 12:45:00 -0.870895  0.820787 -0.153566 -1.583983
2025-11-26 16:45:00  0.520450  0.444356  0.077013  0.345359
2025-11-26 17:45:00  0.028137  1.652969 -1.822554  0.579359
2025-11-26 18:45:00  0.624245  0.716090  1.301692 -0.549737
2025-11-26 19:45:00  0.244254  0.544641  0.827383 -0.450897

In [93]:
# Selecting on the basis of boolean conditions applied to the whole DataFrame
df[df>0]

# a DataFrame with the same shape is returned, with NaN's where condition is not met

                            A         B         C         D
2025-11-26 10:45:00       NaN       NaN  0.511453  1.051404
2025-11-26 11:45:00  1.265489  0.531300       NaN       NaN
2025-11-26 12:45:00       NaN  0.820787       NaN       NaN
2025-11-26 13:45:00  0.910680       NaN  0.302311  1.378908
2025-11-26 14:45:00       NaN       NaN       NaN  1.188936
2025-11-26 15:45:00  1.678756       NaN       NaN  0.588048
2025-11-26 16:45:00  0.520450  0.444356  0.077013  0.345359
2025-11-26 17:45:00  0.028137  1.652969       NaN  0.579359
2025-11-26 18:45:00  0.624245  0.716090  1.301692       NaN
2025-11-26 19:45:00  0.244254  0.544641  0.827383       NaN

### Setting

Combination of selection and setting of values

In [102]:
# setting values by label (same as by position)
df.at[dates[0],'A'] = 0

# setting and assigning a numpy array
df.loc[:,'D'] = np.array([5] * len(df)) # This is "len(df)" times the value 5.

# defining a brend new column
df['E'] = np.arange(len(df))*0.5

# defining a brend new column by means of a pd.Series: indexes must be the same!
df['E prime'] = pd.Series(np.arange(len(df))*2, index=df.index)

df

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -0.471869  0.511453  5.0  0.0        0  1.000000
2025-11-26 11:45:00  1.265489  0.531300 -0.667643  5.0  0.5        2  0.999962
2025-11-26 12:45:00 -0.870895  0.820787 -0.153566  5.0  1.0        4  0.999848
2025-11-26 13:45:00  0.910680 -1.195849  0.302311  5.0  1.5        6  0.999657
2025-11-26 14:45:00 -0.532654 -1.100528 -1.461212  5.0  2.0        8  0.999391
2025-11-26 15:45:00  1.678756 -0.231858 -0.104664  5.0  2.5       10  0.999048
2025-11-26 16:45:00  0.520450  0.444356  0.077013  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.028137  1.652969 -1.822554  5.0  3.5       14  0.998135
2025-11-26 18:45:00  0.624245  0.716090  1.301692  5.0  4.0       16  0.997564
2025-11-26 19:45:00  0.244254  0.544641  0.827383  5.0  4.5       18  0.996917

In [103]:
def dcos(theta):
    theta = theta*(np.pi/180)
    return np.cos(theta)
 
df['cosine'] = pd.Series(df["E"].apply(dcos), index=df.index)
df

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -0.471869  0.511453  5.0  0.0        0  1.000000
2025-11-26 11:45:00  1.265489  0.531300 -0.667643  5.0  0.5        2  0.999962
2025-11-26 12:45:00 -0.870895  0.820787 -0.153566  5.0  1.0        4  0.999848
2025-11-26 13:45:00  0.910680 -1.195849  0.302311  5.0  1.5        6  0.999657
2025-11-26 14:45:00 -0.532654 -1.100528 -1.461212  5.0  2.0        8  0.999391
2025-11-26 15:45:00  1.678756 -0.231858 -0.104664  5.0  2.5       10  0.999048
2025-11-26 16:45:00  0.520450  0.444356  0.077013  5.0  3.0       12  0.998630
2025-11-26 17:45:00  0.028137  1.652969 -1.822554  5.0  3.5       14  0.998135
2025-11-26 18:45:00  0.624245  0.716090  1.301692  5.0  4.0       16  0.997564
2025-11-26 19:45:00  0.244254  0.544641  0.827383  5.0  4.5       18  0.996917

In [104]:
# another example of global setting
df2=df.copy()

df2[df2>0] = -df2
df2

                            A         B         C    D    E  E prime    cosine
2025-11-26 10:45:00  0.000000 -0.471869 -0.511453 -5.0  0.0        0 -1.000000
2025-11-26 11:45:00 -1.265489 -0.531300 -0.667643 -5.0 -0.5       -2 -0.999962
2025-11-26 12:45:00 -0.870895 -0.820787 -0.153566 -5.0 -1.0       -4 -0.999848
2025-11-26 13:45:00 -0.910680 -1.195849 -0.302311 -5.0 -1.5       -6 -0.999657
2025-11-26 14:45:00 -0.532654 -1.100528 -1.461212 -5.0 -2.0       -8 -0.999391
2025-11-26 15:45:00 -1.678756 -0.231858 -0.104664 -5.0 -2.5      -10 -0.999048
2025-11-26 16:45:00 -0.520450 -0.444356 -0.077013 -5.0 -3.0      -12 -0.998630
2025-11-26 17:45:00 -0.028137 -1.652969 -1.822554 -5.0 -3.5      -14 -0.998135
2025-11-26 18:45:00 -0.624245 -0.716090 -1.301692 -5.0 -4.0      -16 -0.997564
2025-11-26 19:45:00 -0.244254 -0.544641 -0.827383 -5.0 -4.5      -18 -0.996917

### Are you dealing with a Copy or a View?

In general is hard to tell..

In [ ]:
dfd = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6]})

# This is likely a view
subset = dfd.loc[0:1, 'a']  
subset[0] = 100  # May affect `df`

print (dfd)

# This is a copy
subset = dfd.loc[[0, 1], 'a']  
subset[0] = 200  # Does NOT affect `df`

print (dfd)

The behaviour depend on the version of Pandas and on the version of Numpy that given version of Pandas depends upon. Since Pandas 1.5 "Copy-on-Write" (CoW) is (optionally) available and as of Pandas 3.0 will be the default. 

With CoW chained assignemt will never work; in the following example, the view `dfd["a"]` and `df` itself are modified in one step. This will lead to a `ChainedAssignemntError`

In [ ]:
dfd["a"][dfd["b"] > 5] = 100
dfd

With copy on write this can be done by using `loc`

In [ ]:
dfd.loc[dfd["b"] > 5, "a"] = 200
dfd

### Dropping

N.B.: dropping doesn't act permanently on the DataFrame, i.e. to get that do :
```python
df = df.drop(....)
```

In [ ]:
# Dropping by column
df.drop(['E prime'], axis=1)

#which is equivalent to
new_df=df.drop(columns=['E prime'])
new_df

In [ ]:
# Dropping by raws
# safe and always working
df.drop(df.index[[1,2,3,4]])

In [ ]:
df

In [ ]:
# something like df.drop('index_name') 
# would work but the type of index must be specificed, 
# in particular with DatetimeIndex
df.drop(pd.to_datetime("2025-11-26 18:45:00"))

## Missing data

pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations.

In [ ]:
df_wNan = df[df>-0.5]
df_wNan

In [ ]:
# dropping raws with at least a Nan
df_wNan.dropna(how='any')

In [ ]:
# getting a mask
df_wNan.isna()
#df_wNan.notna()

In [ ]:
# filling missing data
df_wNan.fillna(value=0)

Fill gaps forward or backward by propagating non-NA values forward or backward:

In [ ]:
df_wNan.fillna(method='pad')

## Operations

Here comes the most relevant advantage of DataFrame. Operations on columns are extremly fast due to several intrinsic optimizations:

* They are implemented in C/Cython via NumPy.
* Pandas processes columns as contiguous memory arrays.
* Vectorized operations eliminate the need for slow Python loops.
* Efficient memory and cache utilization boost performance.

In [ ]:
# Some statistics (mean() just as an example)
# raws
print (df.mean(axis=0),'\n')
# columns
print (df.mean(axis=1),'\n')

In [ ]:
# global operations on columns
df.apply(np.cumsum)

In [ ]:
df

In [ ]:
df.apply(lambda x: x.max() - x.min())

In [ ]:
# syntax is as usual similar to that of numpy arrays
df['A']+df['B']

Let's play it hard and load (in memory) a (relatively) large dataset

In [ ]:
# WARNING! link in past notebook was wrong!, (if needed) get the right file from:
#!wget https://www.dropbox.com/s/xvjzaxzz3ysphme/data_000637.txt -P ~/data/

file_name="~/data/data_000637.txt"
data=pd.read_csv(file_name)
data.tail(10)

Let's now do some operations among (elements of) columns

In [ ]:
# the one-liner killing it all
data['timens']=data['TDC_MEAS']*25/30+data['BX_COUNTER']*25

In [ ]:
data['timens']

In [ ]:
# the old slooow way
def conversion(data):
    result=[]
    for i in range(len(data)): 
        result.append(data.loc[data.index[i],'TDC_MEAS']*25/30.+data.loc[data.index[i],'BX_COUNTER']*25)
    return result

data['timens']=conversion(data)

For tasks on extremely large datasets, libraries like [Polars](https://docs.pola.rs) or [Dask](https://www.dask.org) can offer even faster alternatives by further parallelizing or optimizing columnar operations.

## Merge

pandas provides various facilities for easily combining together Series, DataFrame, and Panel objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

### Concat

concatenation (adding rows) is straightforward

In [ ]:
rdf = pd.DataFrame(np.random.randn(10, 4))
rdf

In [ ]:
# divide it into pieaces raw-wise
pieces = [rdf[:3], rdf[3:7], rdf[7:]]
pieces

In [ ]:
# put it back together
#pd.concat(pieces)

# indexes can be ignored
pd.concat(pieces, ignore_index=True)

# in case of dimension mismatch, Nan are added where needed

In [ ]:
# appending a single row (as a Series)
s = rdf.iloc[3]
rdf = pd.concat([rdf,s.to_frame().T], ignore_index=True)
rdf

### Merge/Join

SQL like operations on table can be performed on DataFrames. This is all rather sophisticated, refer to the [doc](https://pandas.pydata.org/pandas-docs/stable/merging.html#merging) for more info/examples.

#### Merging, Inner Join (default)

Only rows with matching id values are included:

In [ ]:
import pandas as pd

df1 = pd.DataFrame({'id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'id': [2, 3, 4], 'age': [25, 30, 35]})

# Merge on the 'id' column
result = pd.merge(df1, df2, on='id')
print(result)

#### Merging, Left Join

A left join includes all rows from `df1` (left) and fills in `NaN` for missing matches in `df2`.

In [ ]:
result = pd.merge(df2, df1, on='id', how='left')
print(result)

#### Merging, Outer Join

An outer join includes all rows from both DataFrames, filling NaN for missing values

In [ ]:
result = pd.merge(df1, df2, on='id', how='outer')
print(result)

`join` is similar to `merge` but uses index as key and has 'Left' as default

In [ ]:
df1 = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie']}, index=[1, 2, 3])
df2 = pd.DataFrame({'age': [25, 30, 35]}, index=[2, 3, 4])

result = df1.join(df2)
print(result)

## Grouping

By “group by” we are referring to a process involving one or more of the following steps:

* Splitting the data into groups based on some criteria
* Applying a function to each group independently
* Combining the results into a data structure


Grouping is one of the most powerful and at the same time most sofisticated action you can perform with DataFrames. Mastering it is key for an effective usage of Pandas and vectorized data analysis. Reading the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html) or going through a [tutorial](https://realpython.com/pandas-groupby/) is warmly recommended. 

Let's go through a few examples:

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'C'],
    'Values': [10, 20, 30, 40, 50, 60]
}

df = pd.DataFrame(data)

# Group by 'Category' and calculate the sum
result = df.groupby('Category').sum()
print(result)

In [ ]:
# Multiple Aggregations
result = df.groupby('Category').agg(['sum', 'mean'])
print(result)

In [ ]:
# Grouping by multiple columns
df = pd.DataFrame({'Category': ['A', 'A', 'B', 'B', 'C', 'C'],
                   'Type': ['X', 'Y', 'X', 'Y', 'X', 'Y'],
                   'Values': [10, 20, 30, 40, 50, 60]})

result = df.groupby(['Category', 'Type']).sum()
print(result)

In [ ]:
# Trasformations using groupby(): add group averages to DataFrame
df['Group_Avg'] = df.groupby('Category')['Values'].transform('mean')
print(df)

In [ ]:
# filtering
filtered = df.groupby('Category').filter(lambda x: x['Values'].sum() > 50)
print(filtered)

In [ ]:
# custom aggregation with apply()
def custom_aggregation(group):
    return pd.Series({
        'Sum': group['Values'].sum(),
        'Max': group['Values'].max(),
        'Count': group['Values'].count()
    })

result = df.groupby('Category').apply(custom_aggregation)
print(result)

In [ ]:
# splitting data into groups
grouped = df.groupby('Category')

for name, group in grouped:
    print(f"Group: {name}")
    print(group)

## Multi-indexing


Hierarchical / Multi-level indexing allows sophisticated data analysis on higher dimensional data. In essence, it enables you to store and manipulate data with an arbitrary number of dimensions in lower dimensional data structures like Series (1d) and DataFrame (2d).

In [ ]:
tuples = list(zip(['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
          ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']))
multi_index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
print (multi_index,'\n')

s = pd.Series(np.random.randn(8), index=multi_index)
print (s)

In [ ]:
gdf = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                          'foo', 'bar', 'foo', 'foo'],
                    'B' : ['one', 'one', 'two', 'three',
                           'two', 'two', 'one', 'three'],
                    'C' : np.random.randn(8),
                    'D' : np.random.randn(8)})
gdf

# it enables further features of the groupby method,
# e.g. when group-by by multiple columns
gdf.groupby(['A','B']).sum()

In [ ]:
# stack() method “compresses” a level in the DataFrame’s columns
gdf.groupby(['A','B']).sum().stack()

## Plotting

Just a preview, more on the next lab class!

In [ ]:
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts.cumsum().plot()

In [ ]:
import matplotlib.pyplot as plt

pdf=pd.DataFrame(np.random.randn(1000, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
pdf = pdf.cumsum()
plt.figure(); pdf.plot(); plt.legend(loc='best')